"""Zero-silent-failure guarantee for ipa-healthcheck findings.

Every failing result of every upstream check (inventory snapshot of ipa-healthcheck 0.12, 0.16,
0.19 and master, generated by scripts/inventory_healthcheck.py) must end up either cited by a
diagnosis or listed by name in ``undiagnosed_findings`` - never silently dropped. A check that
does not exist yet (or a hostile/malformed one) must never be claimed by an existing rule."""

from __future__ import annotations

import io
import json
import pathlib

import pytest
from rich.console import Console

from ipa_diagnose.engine.model import DiagnosisStatus
from ipa_diagnose.engine.run import run_diagnosis
from ipa_diagnose.evidence.healthcheck import parse_healthcheck_results
from ipa_diagnose.evidence.model import EvidenceBundle, EvidenceItem
from ipa_diagnose.render.console import render_report
from ipa_diagnose.render.json_output import report_to_dict

SNAPSHOT = json.loads((pathlib.Path(__file__).parents[1] / "data" / "healthcheck_inventory.json").read_text(encoding="utf-8"))
FAIL_LEVELS = ("WARNING", "ERROR", "CRITICAL")
GOOD = {
    "source": "ipahealthcheck.meta.services", "check": "dirsrv", "result": "SUCCESS", "uuid": "good",
    "when": "20260101000000Z", "duration": "0.01", "kw": {"status": True},
}


def _entry(source, check, level, key=None, msg=None, uid="x", **kw):
    body = {"key": key or check}
    if msg is not None:
        body["msg"] = msg
    body.update(kw)
    return {"source": source, "check": check, "result": level, "uuid": f"{source}.{check}.{level}.{key}.{uid}",
            "when": "20260101000000Z", "duration": "0.01", "kw": body}


def _bundle(entries, items=()):
    findings = parse_healthcheck_results([GOOD] + list(entries), command="t", live=False)
    return EvidenceBundle(hostname="h", collected_at=EvidenceBundle.now(), findings=findings, items=list(items))


def _rule(report, rule_id):
    return next((d for d in report.diagnoses if d.rule_id == rule_id), None)


def _accounted_for(report, entry):
    cited = {r.evidence_id for d in report.diagnoses for r in list(d.evidence_for) + list(d.evidence_against)}
    listed = {(u.source, u.check) for u in report.undiagnosed_findings}
    return entry["uuid"] in cited or (entry["source"], entry["check"]) in listed


def _rows(tag):
    for cid, info in sorted(SNAPSHOT[tag].items()):
        module = info["module"]
        check = cid[len(module) + 1:]
        levels = [lv for lv in info["levels"] if lv in FAIL_LEVELS] or list(FAIL_LEVELS)
        if info["levels"] == ["SUCCESS"]:
            continue
        for level in levels:
            for key in [None] + list(info["keys"]):
                yield module, check, level, key


@pytest.mark.parametrize("tag", sorted(SNAPSHOT))
def test_every_failing_upstream_check_is_accounted_for(tag):
    silent = []
    total = 0
    for module, check, level, key in _rows(tag):
        for shape in ("msg", "crash"):
            if shape == "msg":
                e = _entry(module, check, level, key, msg=f"synthetic {level} from {check}")
            else:
                e = _entry(module, check, level, key, exception="boom", traceback="Traceback ...")
                e["kw"].pop("key")
            total += 1
            if not _accounted_for(run_diagnosis(_bundle([e])), e):
                silent.append(f"{module}.{check}/{level}/{key}/{shape}")
    assert total > 100
    assert not silent, f"silently unhandled in ipa-healthcheck {tag}: {silent[:10]}"


FUTURE_SOURCES = sorted({v["module"] for v in SNAPSHOT["master"].values()}) + ["ipahealthcheck.zz.brand_new"]


@pytest.mark.parametrize("source", FUTURE_SOURCES)
def test_unknown_future_check_is_surfaced_and_never_claimed_by_a_rule(source):
    for level in FAIL_LEVELS + ("FATAL",):
        for shape in ("msg", "nomsg", "exception", "nokw"):
            e = _entry(source, "ZzFutureCheck", level, msg="a brand new failure" if shape == "msg" else None)
            if shape == "exception":
                e["kw"] = {"exception": "x", "traceback": "y"}
            if shape == "nokw":
                e.pop("kw")
            report = run_diagnosis(_bundle([e]))
            claimed = [d.rule_id for d in report.diagnoses if e["uuid"] in {r.evidence_id for r in d.evidence_for}
                       and d.status == DiagnosisStatus.DIAGNOSED]
            assert not claimed, f"{source}/{level}/{shape} wrongly diagnosed by {claimed}"
            assert _accounted_for(report, e), f"{source}/{level}/{shape} silently dropped"


def test_more_than_the_grouped_limit_of_findings_are_all_named():
    entries = [_entry("ipahealthcheck.zz.brand_new", f"Chk{i}", "ERROR", msg=f"problem {i}") for i in range(15)]
    report = run_diagnosis(_bundle(entries))
    names = {u.check for u in report.undiagnosed_findings}
    cited = {r.evidence_id for d in report.diagnoses for r in d.evidence_for}
    for e in entries:
        assert e["check"] in names or e["uuid"] in cited


# ---- specific rule-exactness regressions -------------------------------------------------------------


def test_expired_directory_server_certificate_is_a_certificate_diagnosis_not_an_nss_format_one():
    e = _entry("ipahealthcheck.ds.nss_ssl", "NssCheck", "CRITICAL", key="DSCERTLE0002",
               msg="The certificate (Server-Cert) has expired", items=["Expiration"])
    report = run_diagnosis(_bundle([e]))
    d = _rule(report, "ds-certificate-expiry")
    assert d is not None and d.status == DiagnosisStatus.DIAGNOSED
    assert "expired" in d.title.lower()
    assert _rule(report, "nss-tls-db-format") is None


def test_unknown_nss_check_result_is_not_a_db_format_or_expiry_diagnosis():
    e = _entry("ipahealthcheck.ds.nss_ssl", "NssCheck", "ERROR", key="DSCERTLE9999", msg="something new")
    report = run_diagnosis(_bundle([e]))
    assert _rule(report, "nss-tls-db-format") is None and _rule(report, "ds-certificate-expiry") is None
    assert any(u.check == "NssCheck" for u in report.undiagnosed_findings) or _rule(report, "unexplained-findings")


def test_umask_warning_is_not_an_ownership_mismatch():
    e = _entry("ipahealthcheck.ipa.files", "IPAFileCheck", "WARNING", type="umask",
               msg="Unexpected umask 0o027 expected 0o022, skipping file permissions.")
    report = run_diagnosis(_bundle([e]))
    assert _rule(report, "ownership-selinux-mismatch") is None
    assert any(u.check == "IPAFileCheck" for u in report.undiagnosed_findings)


def test_filesystem_not_mounted_is_not_disk_exhaustion():
    e = _entry("ipahealthcheck.system.filesystemspace", "FileSystemSpaceCheck", "WARNING", store="/var/log/audit/",
               msg="File system /var/log/audit/ is not mounted")
    report = run_diagnosis(_bundle([e]))
    assert _rule(report, "disk-space-exhaustion") is None
    assert any(u.check == "FileSystemSpaceCheck" for u in report.undiagnosed_findings)


def test_real_shaped_low_free_space_is_still_diagnosed():
    e = _entry("ipahealthcheck.system.filesystemspace", "FileSystemSpaceCheck", "ERROR", store="/var/lib/dirsrv/",
               msg="/var/lib/dirsrv/: free space percentage under threshold: 9% < 20%", percent_free=9, threshold=20)
    assert _rule(run_diagnosis(_bundle([e])), "disk-space-exhaustion") is not None


def test_ca_down_with_error_4301_is_not_an_ra_agent_desync():
    e = _entry("ipahealthcheck.dogtag.ca", "DogtagCertsConnectivityCheck", "ERROR",
               msg="Request for certificate failed: Unable to communicate with CMS")
    j = EvidenceItem(item_id="pj", kind="pki_journal_line", summary="4301",
                     data={"line": "certmonger: failed request, will retry: 4301 (RPC failed at server. Certificate operation cannot be completed: Unable to communicate with CMS)"})
    d = _rule(run_diagnosis(_bundle([e], [j])), "ra-agent-desync")
    assert d is None or d.status != DiagnosisStatus.DIAGNOSED


def test_non_expiry_expiration_check_error_is_not_a_certificate_expired_diagnosis():
    e = _entry("ipahealthcheck.ipa.certs", "IPACertfileExpirationCheck", "ERROR",
               msg="Unable to open NSS database '/etc/dirsrv/slapd-X'", key="nssdb_open")
    report = run_diagnosis(_bundle([e]))
    assert _rule(report, "cert-expired") is None
    assert any(u.check == "IPACertfileExpirationCheck" for u in report.undiagnosed_findings) or _rule(report, "unexplained-findings")


def test_external_certificate_expiry_is_not_given_ipa_cert_fix_advice():
    e = _entry("ipahealthcheck.ipa.certs", "IPACertmongerExpirationCheck", "WARNING", key="123",
               msg="Request id '123' expires in 10 days. This is not an IPA-issued certificate and will not auto-renew.")
    assert _rule(run_diagnosis(_bundle([e])), "cert-expired") is None


def test_amber_or_unfetchable_replication_status_is_not_a_peer_connectivity_diagnosis():
    for key in ("DSREPLLE0003", "DSREPLLE0004", "DSREPLLE0006"):
        e = _entry("ipahealthcheck.ds.replication", "ReplicationCheck", "ERROR", key=key,
                   msg='The replication agreement (meTob.example.test) under "dc=example,dc=test" is not in synchronization.')
        bind = EvidenceItem(item_id="b1", kind="keytab_bind_check", summary="bind failed", data={"bind_ok": False, "peer": "b.example.test"})
        d = _rule(run_diagnosis(_bundle([e], [bind])), "peer-connectivity-break")
        assert d is None, key


def test_lib389_conflict_warning_reaches_the_conflicts_rule():
    e = _entry("ipahealthcheck.ds.replication", "ReplicationCheck", "WARNING", key="DSREPLLE0002",
               msg='There were 3 conflict entries found under the replication suffix "dc=example,dc=test".')
    report = run_diagnosis(_bundle([e]))
    assert _rule(report, "replication-conflicts") is not None


def test_real_topology_disconnected_message_is_recognised():
    e = _entry("ipahealthcheck.ipa.topology", "IPATopologyDomainCheck", "ERROR", type="connect", key="domain-connect",
               msg="Server ipa2.example.test can't contact servers: ipa1.example.test")
    report = run_diagnosis(_bundle([e]))
    assert _accounted_for(report, e)
    assert _rule(report, "topology-disconnected") is not None


# ---- output surfaces -----------------------------------------------------------------------------------


def _hostile_report():
    e = _entry("ipahealthcheck.zz.brand_new", "Evil\x1b[31mCheck", "WARNING",
               msg="$(rm -rf /) `id` \x1b]0;pwn\x07 password=hunter2 " + "A" * 5000)
    return run_diagnosis(_bundle([e]))


def test_json_preserves_undiagnosed_findings_structurally_and_sanitised():
    data = report_to_dict(_hostile_report())
    u = data["undiagnosed_findings"]
    assert u and {"source", "check", "severity", "message", "reason", "check_crashed"} <= set(u[0])
    blob = json.dumps(u)
    assert "\x1b" not in blob and len(u[0]["message"]) <= 300
    assert data["unclaimed_warnings"] == 1  # legacy count key kept for compatibility


def test_console_lists_undiagnosed_findings_by_name_default_and_details():
    report = run_diagnosis(_bundle([
        _entry("ipahealthcheck.zz.brand_new", "OddCheck", "WARNING", msg="odd but not fatal"),
    ]))
    for details in (False, True):
        buf = io.StringIO()
        render_report(report, Console(file=buf, width=140, force_terminal=False), details=details)
        out = buf.getvalue()
        assert "UNDIAGNOSED" in out and "OddCheck" in out and "odd but not fatal" in out
    assert "check available since" in out or "not in this build" in out  # --details adds version context


def test_known_check_reports_the_upstream_release_it_first_appeared_in():
    report = run_diagnosis(_bundle([_entry("ipahealthcheck.ipa.dna", "IPADNARangeCheck", "WARNING", msg="odd")]))
    u = next(u for u in report.undiagnosed_findings if u.check == "IPADNARangeCheck")
    assert u.check_known_since is not None


def test_critical_ds_certificate_expiry_keeps_critical_severity():
    e = _entry("ipahealthcheck.ds.nss_ssl", "NssCheck", "CRITICAL", key="DSCERTLE0002", msg="The certificate (Server-Cert) has expired")
    assert _rule(run_diagnosis(_bundle([e])), "ds-certificate-expiry").severity.value == "CRITICAL"


def test_json_flags_undiagnosed_findings_even_when_overall_is_healthy():
    report = run_diagnosis(_bundle([_entry("ipahealthcheck.zz.brand_new", "OddCheck", "WARNING", msg="odd")]))
    data = report_to_dict(report)
    assert data["has_undiagnosed_findings"] is True and data["undiagnosed_count"] == 1
    assert report_to_dict(run_diagnosis(_bundle([])))["has_undiagnosed_findings"] is False


def test_duplicate_uuids_do_not_hide_a_failing_finding():
    a = _entry("ipahealthcheck.zz.brand_new", "A", "ERROR", msg="one")
    b = dict(_entry("ipahealthcheck.zz.brand_new", "B", "WARNING", msg="two"), uuid=a["uuid"])
    report = run_diagnosis(_bundle([a, b]))
    names = {u.check for u in report.undiagnosed_findings} | {r.evidence_id for d in report.diagnoses for r in d.evidence_for}
    assert "B" in names or any("B" in str(n) for n in names) or len(report.undiagnosed_findings) >= 1


def test_details_output_is_bounded_and_secrets_are_masked_with_thousands_of_findings():
    import time

    entries = [_entry("ipahealthcheck.zz.brand_new", f"C{i}", "WARNING", msg="key sk-abcdefghijklmnopqrstuvwx " + "x" * 300) for i in range(1500)]
    report = run_diagnosis(_bundle(entries))
    assert len(report.undiagnosed_findings) == 1500
    assert all("sk-abcdefgh" not in u.message for u in report.undiagnosed_findings)
    buf = io.StringIO()
    start = time.monotonic()
    render_report(report, Console(file=buf, width=140, force_terminal=False), details=True)
    assert time.monotonic() - start < 20
    assert "and 1300 more" in buf.getvalue()


def test_message_placeholders_and_keys_make_identical_findings_distinguishable():
    e = _entry("ipahealthcheck.ipa.idns", "IPADNSSystemRecordsCheck", "WARNING", key="_ldap._tcp.x.test.", msg="Expected SRV record missing")
    u = run_diagnosis(_bundle([e])).undiagnosed_findings
    u = [x for x in u if x.check == "IPADNSSystemRecordsCheck"]
    assert u and u[0].key == "_ldap._tcp.x.test."
    e2 = _entry("ipahealthcheck.ipa.idns", "IPADNSSystemRecordsCheck", "WARNING", msg="missing IP address for ipa-ca server {server}", server="ipa1.test")
    u2 = run_diagnosis(_bundle([e2])).undiagnosed_findings
    assert any("ipa1.test" in x.message and "{server}" not in x.message for x in u2)


def test_message_placeholders_never_evaluate_format_expressions():
    e = _entry("ipahealthcheck.zz.brand_new", "Fmt", "WARNING", msg="{a.__class__} {0} {:>99999999} {server.__init__} {server}", server="ipa1")
    u = run_diagnosis(_bundle([e])).undiagnosed_findings[0]
    assert "<class" not in u.message and "ipa1" in u.message and len(u.message) <= 300


# ---- false-diagnosis gate regressions (adversarial review of the 0.1.3 candidate) ----------------------


def _diag_ids(report):
    return {d.rule_id for d in report.diagnoses if d.status == DiagnosisStatus.DIAGNOSED}


def test_ca_down_is_not_an_ra_agent_desync_even_with_ra_cm_failure_or_ldap_access_error():
    cm = EvidenceItem(item_id="cm1", kind="certmonger_request", summary="ra",
                      data={"nickname": "ipaCert", "state": "CA_UNREACHABLE", "request_id": "1"})
    e = _entry("ipahealthcheck.dogtag.ca", "DogtagCertsConnectivityCheck", "ERROR", msg="CA down")
    j = EvidenceItem(item_id="pj", kind="pki_journal_line", summary="x", data={"line": "LDAP: Insufficient access on ou=people"})
    assert "ra-agent-desync" not in _diag_ids(run_diagnosis(_bundle([e], [cm, j])))


def test_ra_agent_message_words_do_not_make_a_desync_only_its_keys_do():
    e = _entry("ipahealthcheck.ipa.certs", "IPARAAgent", "ERROR", msg="Unable to connect to mismatch.example.com")
    assert "ra-agent-desync" not in _diag_ids(run_diagnosis(_bundle([e])))
    e2 = _entry("ipahealthcheck.ipa.certs", "IPARAAgent", "ERROR", key="description_mismatch", msg="RA agent description differs")
    assert "ra-agent-desync" in _diag_ids(run_diagnosis(_bundle([e2])))


def test_expiry_word_in_a_path_is_not_an_expired_certificate():
    e = _entry("ipahealthcheck.ipa.certs", "IPACertmongerExpirationCheck", "ERROR",
               msg="Unable to determine expiration: NSS db /etc/pki/expired-certs not readable")
    assert "cert-expired" not in _diag_ids(run_diagnosis(_bundle([e])))


def test_file_findings_need_owner_group_mode_shape():
    e = _entry("ipahealthcheck.ipa.files", "IPAFileCheck", "ERROR", msg="File /etc/dirsrv/x does not exist")
    assert "ownership-selinux-mismatch" not in _diag_ids(run_diagnosis(_bundle([e])))
    e2 = _entry("ipahealthcheck.ipa.files", "IPAFileCheck", "ERROR", key="/etc/x", path="/etc/x", type="mode",
                expected="0640", got="0600", msg="Permissions of /etc/x are too restrictive: 0600 and should be 0640")
    assert "ownership-selinux-mismatch" in _diag_ids(run_diagnosis(_bundle([e2])))


def test_missing_index_needs_the_exact_key_source_and_check():
    e = _entry("ipahealthcheck.ds.backends", "BackendsCheck", "ERROR", key="DSBLE0003", msg="see DSBLE0007 docs")
    e2 = _entry("ipahealthcheck.ds.backends_extra", "Foo", "ERROR", key="DSBLE0007", msg="x")
    assert "missing-system-index" not in _diag_ids(run_diagnosis(_bundle([e, e2])))
    e3 = _entry("ipahealthcheck.ds.backends", "BackendsCheck", "ERROR", key="DSBLE0007", msg="Missing indexes")
    assert "missing-system-index" in _diag_ids(run_diagnosis(_bundle([e3])))


def test_named_down_needs_the_exact_service_result():
    e = _entry("ipahealthcheck.meta.services", "httpd", "ERROR", msg="httpd: not running", note="renamed")
    e2 = _entry("ipahealthcheck.ipa.zz", "IPAServiceCheck", "ERROR", msg="Service unnamed failed")
    assert "named-service-down" not in _diag_ids(run_diagnosis(_bundle([e, e2])))
    e3 = _entry("ipahealthcheck.meta.services", "named", "ERROR", msg="named: not running")
    assert "named-service-down" in {d.rule_id for d in run_diagnosis(_bundle([e3])).diagnoses}


def test_other_nsscheck_result_next_to_db_journal_is_not_a_confident_db_format_diagnosis():
    e = _entry("ipahealthcheck.ds.nss_ssl", "NssCheck", "ERROR", key="DSCERTLE0009", msg="hostname does not match")
    j = EvidenceItem(item_id="j1", kind="dirsrv_journal_line", summary="x",
                     data={"category": "nss_tls", "message": "SEC_ERROR_BAD_DATABASE: cert9.db"})
    assert "nss-tls-db-format" not in _diag_ids(run_diagnosis(_bundle([e], [j])))
