"""Generate the embedded ipa-healthcheck check catalog from an inventory JSON.

Input is the output of scripts/inventory_healthcheck.py. Writes

  * src/ipa_diagnose/evidence/healthcheck_catalog.py - for every upstream check
    ("<source>.<Check>"), the first and last upstream release it was seen in
    (last is "master" while it is still present). Used only to give an
    unexplained finding version context ("known since 0.16") - never to decide
    whether something is healthy.
  * tests/data/healthcheck_inventory.json - levels/keys per check for a few
    representative releases; the zero-silent-failure tests feed every one of
    them through the real engine.

Usage: python scripts/gen_healthcheck_catalog.py INVENTORY.json
"""

from __future__ import annotations

import json
import re
import sys

SNAPSHOT_TAGS = ["0.12", "0.16", "0.19", "master"]


def _ver(tag: str):
    m = re.search(r"(\d+)\.(\d+)", tag)
    return (int(m.group(1)), int(m.group(2))) if m else (10**6, 0)


def main(argv):
    inv = json.load(open(argv[1], encoding="utf-8"))
    tags = sorted((t for t in inv if t != "release-0.1"), key=_ver)
    tags = [t for t in tags if t != "master"]
    ids = sorted({cid for t in inv for cid in inv[t]})
    lines = [
        '"""Generated by scripts/gen_healthcheck_catalog.py - do not edit.',
        "",
        "Upstream ipa-healthcheck check -> (first release seen, last release seen). Context only.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import Dict, Tuple",
        "",
        "CATALOG: Dict[str, Tuple[str, str]] = {",
    ]
    for cid in ids:
        present = [t for t in tags if cid in inv[t]]
        if not present and "release-0.1" in inv and cid in inv["release-0.1"]:
            present = ["0.1"]
        first = present[0] if present else "master"
        last = "master" if cid in inv.get("master", {}) else (present[-1] if present else "master")
        lines.append(f'    "{cid}": ("{first}", "{last}"),')
    lines += ["}", ""]
    with open("src/ipa_diagnose/evidence/healthcheck_catalog.py", "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines))
    snap = {t: inv[t] for t in SNAPSHOT_TAGS if t in inv}
    with open("tests/data/healthcheck_inventory.json", "w", encoding="utf-8", newline="\n") as fh:
        json.dump(snap, fh, indent=1, sort_keys=True)
        fh.write("\n")
    print(len(ids), "checks;", "snapshot:", {t: len(v) for t, v in snap.items()})
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
